//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SallikasuServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public merchant()
        {
            this.advertiser_exclusion_dates = new HashSet<advertiser_exclusion_dates>();
            this.advertiser_staff_cell_phone_numbers = new HashSet<advertiser_staff_cell_phone_numbers>();
            this.amenities = new HashSet<amenity>();
            this.bills = new HashSet<bill>();
            this.biz_hours = new HashSet<biz_hours>();
            this.monthly_bills = new HashSet<monthly_bills>();
            this.merchant_advertisers = new HashSet<merchant_advertisers>();
            this.nastha_credits = new HashSet<nastha_credits>();
            this.nastha_redemptions = new HashSet<nastha_redemptions>();
            this.orders = new HashSet<order>();
            this.pictures = new HashSet<picture>();
            this.products = new HashSet<product>();
            this.registration_codes = new HashSet<registration_codes>();
            this.tokens = new HashSet<token>();
            this.tos_agreements = new HashSet<tos_agreements>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string sublocality { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string country { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<float> longitude { get; set; }
        public string thumbnail_photo_url { get; set; }
        public string type { get; set; }
        public string phone { get; set; }
        public string referred_phone_number { get; set; }
        public string permanent_cell_phone_number { get; set; }
        public string website { get; set; }
        public Nullable<decimal> rating { get; set; }
        public string advertiser { get; set; }
        public string opt_out { get; set; }
        public Nullable<int> cumulative_referrals { get; set; }
        public string black_listed { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string place_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<advertiser_exclusion_dates> advertiser_exclusion_dates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<advertiser_staff_cell_phone_numbers> advertiser_staff_cell_phone_numbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amenity> amenities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<biz_hours> biz_hours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<monthly_bills> monthly_bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchant_advertisers> merchant_advertisers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nastha_credits> nastha_credits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nastha_redemptions> nastha_redemptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<picture> pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registration_codes> registration_codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<token> tokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tos_agreements> tos_agreements { get; set; }
    }
}
