//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SallikasuServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class referred_users
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string referred_user_email_address { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
