//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SallikasuServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_configs
    {
        public string tag { get; set; }
        public string value { get; set; }
        public string country { get; set; }
        public string server_or_app { get; set; }
        public int id { get; set; }
    }
}
