//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthly_bills
    {
        public int id { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public Nullable<int> cumul_bill_amt { get; set; }
        public Nullable<int> total_bills { get; set; }
        public Nullable<decimal> cumul_amt_free_cbk { get; set; }
        public Nullable<decimal> cumul_expcbk_today { get; set; }
        public Nullable<decimal> cumul_exp_cbk_pday { get; set; }
        public Nullable<decimal> cumul_comm_today { get; set; }
        public Nullable<decimal> cumul_comm_pday { get; set; }
        public Nullable<decimal> forfeited_amt_today { get; set; }
        public Nullable<decimal> forfeited_amt_pday { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual merchant merchant { get; set; }
    }
}
