//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextSearchRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public merchant()
        {
            this.pictures = new HashSet<picture>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string sublocality { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string country { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<float> longitude { get; set; }
        public string thumbnail_photo_url { get; set; }
        public string type { get; set; }
        public string phone { get; set; }
        public string referred_phone_number { get; set; }
        public string permanent_cell_phone_number { get; set; }
        public string website { get; set; }
        public Nullable<decimal> rating { get; set; }
        public string advertiser { get; set; }
        public string opt_out { get; set; }
        public Nullable<int> cumulative_referrals { get; set; }
        public string black_listed { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string place_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<picture> pictures { get; set; }
    }
}
