//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nastha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        public int id { get; set; }
        public Nullable<decimal> commission_percentage { get; set; }
        public Nullable<decimal> deposit { get; set; }
        public Nullable<decimal> min_deposit_balance { get; set; }
    }
}
