//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nastha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tos_agreements
    {
        public int id { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public Nullable<System.DateTime> agreement_time { get; set; }
        public string agreement_file { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual merchant merchant { get; set; }
    }
}
