//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nastha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_merchant_referrals
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public string cell_phone_entered_by_user { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
